"use client";
import { useEffect, useState } from "react";
import Workspace from "../components/Workspace";
import { useAuth } from "../components/AuthProvider";
import { useNotifier } from "../components/NotificationProvider";
import { apiBaseUrl, apiRequest } from "../../lib/api";
import ErrorState from "../components/ErrorState";
type Message = { message_id: string; run_id: string; source_id: string; error: string };
export default function DlqPage() { const { token } = useAuth(); const notify = useNotifier(); const [items, setItems] = useState<Message[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = () => { if (!token) return; setLoading(true); setError(""); apiRequest<Message[]>(apiBaseUrl, "/api/v1/dlq", token).then((r) => setItems(r.data)).catch((e) => setError(String(e))).finally(() => setLoading(false)); }; useEffect(() => { load(); }, [token]); async function replay(id: string) { try { await apiRequest(apiBaseUrl, `/api/v1/dlq/${encodeURIComponent(id)}/replay`, token, { method: "POST" }); notify("消息已提交重放", "success"); load(); } catch (cause) { notify(String(cause), "error"); } } return <Workspace title="死信队列"><section className="catalog-header"><div><h2>死信队列 <span>{items.length}</span></h2><p>查看失败消息并重新提交可重放的运行。</p></div><button className="secondary-button" onClick={load}>刷新</button></section>{loading ? <ErrorState state="loading" loadingMessage="正在加载死信消息..." /> : error ? <ErrorState state="error" error={error} onRetry={load} /> : items.length === 0 ? <ErrorState state="empty" emptyMessage="当前没有死信消息" /> : <section className="agent-directory-grid" aria-label="死信消息列表">{items.map((item) => <article className="agent-directory-card" key={item.message_id}><div className="agent-card-head"><span className="badge failed">失败</span><code>{item.message_id}</code></div><div className="agent-directory-copy"><h3>Run {item.run_id || "未知"}</h3><p>{item.error || "未记录错误原因"}</p><small>来源：{item.source_id || "未知"}</small></div><div className="agent-directory-actions"><button onClick={() => void replay(item.message_id)}>重放</button></div></article>)}</section>}</Workspace>; }
