"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import Workspace from "../../components/Workspace";
import Input from "../../components/Input";
import { useAuth } from "../../components/AuthProvider";
import { useNotifier } from "../../components/NotificationProvider";
import { apiBaseUrl, apiRequest } from "../../../lib/api";
import ErrorState from "../../components/ErrorState";
type Quota = { tenant_id: string; monthly_token_limit: number; monthly_cost_limit_usd: number; max_concurrent_runs: number; warning_percent: number; max_requests_per_minute: number; max_knowledge_documents: number; max_workflow_runs_per_day: number; usage: { total_tokens: number; cost_usd: number; run_count: number; active_runs: number } };
export default function TenantPage() { const { token, user } = useAuth(); const notify = useNotifier(); const [quota, setQuota] = useState<Quota | null>(null); const [error, setError] = useState(""); const load = () => { if (!token) return; setError(""); apiRequest<Quota>(apiBaseUrl, "/api/v1/settings/tenant", token).then((r) => setQuota(r.data)).catch((e) => setError(String(e))); }; useEffect(() => { load(); }, [token]); async function save(e: FormEvent) { e.preventDefault(); if (!quota) return; try { const { usage, tenant_id, ...payload } = quota; const r = await apiRequest<Quota>(apiBaseUrl, "/api/v1/settings/tenant", token, { method: "PUT", body: JSON.stringify(payload) }); setQuota(r.data); notify("租户配额已保存", "success"); } catch (cause) { notify(String(cause), "error"); } } return <Workspace title="租户配额"><section className="catalog-header"><div><h2>租户配额管理</h2><p>管理员可查看和调整当前租户的资源配额。</p></div><Link className="btn btn-secondary" href="/admin/users">成员管理</Link></section>{error ? <ErrorState state="error" error={error} onRetry={load} /> : !quota ? <ErrorState state="loading" loadingMessage="正在加载配额..." /> : <><form className="panel settings-form" onSubmit={save}><h2>配额设置</h2><div className="form-grid">{([['monthly_token_limit','月度 Token 限制'],['monthly_cost_limit_usd','月度成本限制（USD）'],['max_concurrent_runs','最大并发 Run'],['warning_percent','警告阈值（%）'],['max_requests_per_minute','每分钟请求数'],['max_knowledge_documents','知识库文档数'],['max_workflow_runs_per_day','每日工作流 Run 数']] as const).map(([key, label]) => <label key={key}><span className="label-text">{label}</span><Input type="number" min="0" value={quota[key]} onChange={(e) => setQuota({ ...quota, [key]: Number(e.target.value) })} /></label>)}</div><div className="form-actions"><button className="btn-primary" disabled={user?.role !== "admin" && user?.role !== "tenant_admin"}>保存配额</button></div></form><section className="panel"><h2>当前用量</h2><dl className="detail-list"><div><dt>Token</dt><dd>{quota.usage.total_tokens}</dd></div><div><dt>成本</dt><dd>${quota.usage.cost_usd.toFixed(4)}</dd></div><div><dt>运行次数</dt><dd>{quota.usage.run_count}</dd></div><div><dt>活跃运行</dt><dd>{quota.usage.active_runs}</dd></div></dl></section></>}</Workspace>; }
