"""add tool calls and run output

Revision ID: d8649e9eb831
Revises: 69be6327eb99
"""
import sqlalchemy as sa
from alembic import op

revision = 'd8649e9eb831'
down_revision = '69be6327eb99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_definitions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('executor', sa.String(length=100), nullable=False),
    sa.Column('input_schema', sa.JSON(), nullable=False),
    sa.Column('output_schema', sa.JSON(), nullable=False),
    sa.Column('side_effects', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_tools_tenant_name_version')
    )
    op.create_index(op.f('ix_tool_definitions_name'), 'tool_definitions', ['name'], unique=False)
    op.create_index(op.f('ix_tool_definitions_status'), 'tool_definitions', ['status'], unique=False)
    op.create_index(op.f('ix_tool_definitions_tenant_id'), 'tool_definitions', ['tenant_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('tool_definition_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tool_definition_id'], ['tool_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_tool_calls_tenant_idempotency')
    )
    op.create_index(op.f('ix_tool_calls_run_id'), 'tool_calls', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_status'), 'tool_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tool_calls_tenant_id'), 'tool_calls', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_definition_id'), 'tool_calls', ['tool_definition_id'], unique=False)
    op.add_column('runs', sa.Column('output_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'output_json')
    op.drop_index(op.f('ix_tool_calls_tool_definition_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_tenant_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_status'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_run_id'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_tool_definitions_tenant_id'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_status'), table_name='tool_definitions')
    op.drop_index(op.f('ix_tool_definitions_name'), table_name='tool_definitions')
    op.drop_table('tool_definitions')
    # ### end Alembic commands ###
