"""Generate lightweight Python and TypeScript types from the runtime JSON Schema."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA = ROOT / "project/docs/schemas/runtime-contract.schema.json"


def type_name(name: str) -> str:
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_"))


def ts_type(schema: dict) -> str:
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "$ref" in schema:
        return "string"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "object": "Record<string, unknown>", "null": "null"}.get(schema.get("type"), "unknown")


def py_type(schema: dict) -> str:
    if "enum" in schema:
        return "Literal[" + ", ".join(repr(value) for value in schema["enum"]) + "]"
    if "anyOf" in schema:
        return " | ".join(py_type(item) for item in schema["anyOf"])
    if "$ref" in schema:
        return "str"
    return {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "object": "dict[str, Any]", "null": "None"}.get(schema.get("type"), "Any")


def render(document: dict) -> tuple[str, str]:
    ts = ["// Generated by scripts/generate_contract_types.py. Do not edit.\n"]
    py = ["# Generated by scripts/generate_contract_types.py. Do not edit.\n", "from typing import Any, Literal, TypedDict\n"]
    for name, definition in document["$defs"].items():
        if definition.get("type") != "object":
            continue
        required = set(definition.get("required", [])); class_name = type_name(name)
        ts.append(f"export interface {class_name} {{")
        py.append(f"\nclass {class_name}(TypedDict, total=False):")
        for field, field_schema in definition.get("properties", {}).items():
            ts.append(f"  {field}{'' if field in required else '?'}: {ts_type(field_schema)};")
            py.append(f"    {field}: {py_type(field_schema)}")
        ts.append("}\n")
    return "\n".join(ts), "\n".join(py) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(); parser.add_argument("--check", action="store_true"); args = parser.parse_args()
    ts, py = render(json.loads(SCHEMA.read_text(encoding="utf-8")))
    outputs = {ROOT / "web/lib/generated/runtime-contract.ts": ts, ROOT / "app/generated/runtime_contract.py": py}
    for path, content in outputs.items():
        if args.check and (not path.exists() or path.read_text(encoding="utf-8") != content):
            raise SystemExit(f"GENERATED_CONTRACT_OUTDATED:{path.relative_to(ROOT)}")
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True); path.write_text(content, encoding="utf-8")
    print("contract-types-ok")


if __name__ == "__main__":
    main()
